export const CHAT_HISTORY_FETCH_TIMEOUT_MS = 3000;
export const CHAT_HISTORY_FALLBACK_INITIAL_DELAY_MS = 1200;
export const CHAT_HISTORY_FALLBACK_RETRY_DELAY_MS = 1800;
export const CHAT_HISTORY_FALLBACK_MAX_ATTEMPTS = 120;
export const CHAT_HISTORY_FINAL_RETRY_DELAY_MS = 750;
